{"name": "Тест успешной авторизации", "status": "broken", "statusDetails": {"message": "PermissionError: [WinError 5] Access is denied: 'allure-results\\\\11be1af7-f7a3-445f-a899-e8d1e31ad7fb-result.json'", "trace": "@pytest.fixture(scope=\"session\", autouse=True)\n    def clean_allure_results():\n        # Очистка папки allure-results перед запуском тестов\n        if os.path.exists(\"allure-results\"):\n            try:\n>               shutil.rmtree(\"allure-results\")\n\nconftest.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Python312\\Lib\\shutil.py:796: in rmtree\n    return _rmtree_unsafe(path, onexc)\nC:\\Python312\\Lib\\shutil.py:636: in _rmtree_unsafe\n    onexc(os.unlink, fullname, err)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\npath = 'allure-results'\nonexc = <function rmtree.<locals>.onexc at 0x0000021749AF6C00>\n\n    def _rmtree_unsafe(path, onexc):\n        try:\n            with os.scandir(path) as scandir_it:\n                entries = list(scandir_it)\n        except OSError as err:\n            onexc(os.scandir, path, err)\n            entries = []\n        for entry in entries:\n            fullname = entry.path\n            try:\n                is_dir = entry.is_dir(follow_symlinks=False)\n            except OSError:\n                is_dir = False\n    \n            if is_dir and not entry.is_junction():\n                try:\n                    if entry.is_symlink():\n                        # This can only happen if someone replaces\n                        # a directory with a symlink after the call to\n                        # os.scandir or entry.is_dir above.\n                        raise OSError(\"Cannot call rmtree on a symbolic link\")\n                except OSError as err:\n                    onexc(os.path.islink, fullname, err)\n                    continue\n                _rmtree_unsafe(fullname, onexc)\n            else:\n                try:\n>                   os.unlink(fullname)\nE                   PermissionError: [WinError 5] Access is denied: 'allure-results\\\\11be1af7-f7a3-445f-a899-e8d1e31ad7fb-result.json'\n\nC:\\Python312\\Lib\\shutil.py:634: PermissionError"}, "start": 1736988136427, "stop": 1736988136427, "uuid": "e1e33963-1f1e-4cfb-991b-52224bbf1387", "historyId": "b46a5494b1938ff0bc1144562162876a", "testCaseId": "b46a5494b1938ff0bc1144562162876a", "fullName": "tests.test_login_page.TestLogin#test_validLogin", "labels": [{"name": "story", "value": "Проверка успешной авторизации"}, {"name": "feature", "value": "Тесты для авторизации"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_page"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-M99MFDK"}, {"name": "thread", "value": "6556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_page"}]}