{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","children":[{"name":"test_all_users","uid":"f7f4666a6e34ee22","parentUid":"847622b8b3b23d262bdee3fb9c5ac676","status":"broken","time":{"start":1736978184849,"stop":1736978184849,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["@pytest.mark.usefixtures('db_connection')"]},{"name":"test_user_by_id","uid":"a61824091c31a513","parentUid":"847622b8b3b23d262bdee3fb9c5ac676","status":"broken","time":{"start":1736978185188,"stop":1736978185188,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["@pytest.mark.usefixtures('db_connection')"]}],"uid":"847622b8b3b23d262bdee3fb9c5ac676"}],"uid":"bdbf199525818fae7a8651db9eafe741"},{"name":"Product defects","children":[{"name":"AssertionError: FAILURE: Ожидался статус код 404, но получен 200\nassert 200 == 404\n +  where 200 = <Response [200]>.status_code\ntest_json_placeholder.py:89 in test_delete_post() -> with check:\ntest_json_placeholder.py:90 in test_delete_post -> assert response.status_code == 404, f\"Ожидался статус код 404, но получен {response.status_code}\"\nAssertionError: Ожидался статус код 404, но получен 200\nassert 200 == 404\n +  where 200 = <Response [200]>.status_code\n\n\n------------------------------------------------------------\nFailed Checks: 1","children":[{"name":"test_delete_post","uid":"382816a2fb5dfc5c","parentUid":"5b7f9cd21c76c199bc740242e050b700","status":"failed","time":{"start":1736978184852,"stop":1736978185186,"duration":334},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"5b7f9cd21c76c199bc740242e050b700"},{"name":"AssertionError: FAILURE: assert 'OrangeHRM' == 'OrangeHRMM'\n  \n  - OrangeHRMM\n  ?          -\n  + OrangeHRM\ntest_login_page.py:27 in test_validLogin() -> with check:\ntest_login_page.py:28 in test_validLogin -> assert self.lp.verifyTitle() == \"OrangeHRMM\"\nAssertionError: assert 'OrangeHRM' == 'OrangeHRMM'\n  \n  - OrangeHRMM\n  ?          -\n  + OrangeHRM\n\n\n------------------------------------------------------------\nFailed Checks: 1","children":[{"name":"Тест успешной авторизации","uid":"de906ab8cc76a7b4","parentUid":"68f94e92b8f5ee801d177699b74d7e83","status":"failed","time":{"start":1736978186327,"stop":1736978188761,"duration":2434},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"68f94e92b8f5ee801d177699b74d7e83"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}