{"uid":"7dac49c27302ca58","name":"test_all_users","fullName":"tests.db_testing.test_db.TestDatabase#test_all_users","historyId":"cec67243de9ea25fa276523606e76c0e","time":{"start":1736988945003,"stop":1736988945003,"duration":0},"status":"skipped","statusMessage":"Skipped: База данных недоступна","statusTrace":"('/home/runner/work/make_page_object/make_page_object/tests/db_testing/test_db.py', 15, 'Skipped: База данных недоступна')","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"clean_allure_results","time":{"start":1736988945004,"stop":1736988945005,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"db_connection","time":{"start":1736988945005,"stop":1736988945019,"duration":14},"status":"skipped","statusMessage":"Skipped: База данных недоступна\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/make_page_object/make_page_object/conftest.py\", line 61, in db_connection\n    pytest.skip(\"База данных недоступна\")\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/_pytest/outcomes.py\", line 160, in skip\n    raise Skipped(msg=reason, allow_module_level=allow_module_level)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('db_connection')"},{"name":"parentSuite","value":"tests.db_testing"},{"name":"suite","value":"test_db"},{"name":"subSuite","value":"TestDatabase"},{"name":"host","value":"fv-az1689-883"},{"name":"thread","value":"3294-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.db_testing.test_db"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.usefixtures('db_connection')"]},"source":"7dac49c27302ca58.json","parameterValues":[]}