{"uid":"9570e384373da9eb","name":"test_all_users","fullName":"tests.db_testing.test_db.TestDatabase#test_all_users","historyId":"cec67243de9ea25fa276523606e76c0e","time":{"start":1736988136294,"stop":1736988136294,"duration":0},"status":"broken","statusMessage":"PermissionError: [WinError 5] Access is denied: 'allure-results\\\\11be1af7-f7a3-445f-a899-e8d1e31ad7fb-result.json'","statusTrace":"@pytest.fixture(scope=\"session\", autouse=True)\n    def clean_allure_results():\n        # Очистка папки allure-results перед запуском тестов\n        if os.path.exists(\"allure-results\"):\n            try:\n>               shutil.rmtree(\"allure-results\")\n\nconftest.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Python312\\Lib\\shutil.py:796: in rmtree\n    return _rmtree_unsafe(path, onexc)\nC:\\Python312\\Lib\\shutil.py:636: in _rmtree_unsafe\n    onexc(os.unlink, fullname, err)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\npath = 'allure-results'\nonexc = <function rmtree.<locals>.onexc at 0x0000021749AF6C00>\n\n    def _rmtree_unsafe(path, onexc):\n        try:\n            with os.scandir(path) as scandir_it:\n                entries = list(scandir_it)\n        except OSError as err:\n            onexc(os.scandir, path, err)\n            entries = []\n        for entry in entries:\n            fullname = entry.path\n            try:\n                is_dir = entry.is_dir(follow_symlinks=False)\n            except OSError:\n                is_dir = False\n    \n            if is_dir and not entry.is_junction():\n                try:\n                    if entry.is_symlink():\n                        # This can only happen if someone replaces\n                        # a directory with a symlink after the call to\n                        # os.scandir or entry.is_dir above.\n                        raise OSError(\"Cannot call rmtree on a symbolic link\")\n                except OSError as err:\n                    onexc(os.path.islink, fullname, err)\n                    continue\n                _rmtree_unsafe(fullname, onexc)\n            else:\n                try:\n>                   os.unlink(fullname)\nE                   PermissionError: [WinError 5] Access is denied: 'allure-results\\\\11be1af7-f7a3-445f-a899-e8d1e31ad7fb-result.json'\n\nC:\\Python312\\Lib\\shutil.py:634: PermissionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"clean_allure_results","time":{"start":1736988136296,"stop":1736988136297,"duration":1},"status":"broken","statusMessage":"PermissionError: [WinError 5] Access is denied: 'allure-results\\\\11be1af7-f7a3-445f-a899-e8d1e31ad7fb-result.json'\n","statusTrace":"  File \"C:\\PycharmProjects\\Frameworks\\Selenium_FW_1\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\PycharmProjects\\Frameworks\\Selenium_FW_1\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\PycharmProjects\\Frameworks\\Selenium_FW_1\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\PycharmProjects\\Frameworks\\Selenium_FW_1\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\PycharmProjects\\Frameworks\\Selenium_FW_1\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\PycharmProjects\\Tasks\\Selenium\\make_page_object_model\\conftest.py\", line 35, in clean_allure_results\n    shutil.rmtree(\"allure-results\")\n  File \"C:\\Python312\\Lib\\shutil.py\", line 796, in rmtree\n    return _rmtree_unsafe(path, onexc)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\shutil.py\", line 636, in _rmtree_unsafe\n    onexc(os.unlink, fullname, err)\n  File \"C:\\Python312\\Lib\\shutil.py\", line 634, in _rmtree_unsafe\n    os.unlink(fullname)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('db_connection')"},{"name":"parentSuite","value":"tests.db_testing"},{"name":"suite","value":"test_db"},{"name":"subSuite","value":"TestDatabase"},{"name":"host","value":"DESKTOP-M99MFDK"},{"name":"thread","value":"6556-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.db_testing.test_db"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.usefixtures('db_connection')"]},"source":"9570e384373da9eb.json","parameterValues":[]}